In [3]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as sm
Location = "C:/Akhil/USF BAIS/Data Vis/gradedata.xlsx"
df = pd.read_excel(Location)
df.tail()

,fname,lname,gender,age,exercise,hours,grade,address
1995,Cody,Shepherd,male,19,1,8,80.1,"8567 Walnut Street , Piqua, OH 45356"
1996,Geraldine,Peterson,female,16,4,18,100.0,"Lynn, MA 01902, 66 Bridge Drive"
1997,Mercedes,Leon,female,18,3,14,84.9,"Loxahatchee, FL 33470, 8887 NE. Sugar Road"
1998,Lucius,Rowland,male,16,1,7,69.1,"8734 South Birch Hill Drive , Canfield, OH 44406"
1999,Linus,Morris,male,19,4,10,79.6,"21 Glen Ridge St. , Highland, IN 46322"

In [21]:
df1=df[['grade','exercise', 'hours', 'gender']]
df1= pd.get_dummies(df1, drop_first=True)
result = sm.ols(formula='grade ~ exercise + hours + gender_male',data=df1).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  grade   R-squared:                       0.665
Model:                            OLS   Adj. R-squared:                  0.664
Method:                 Least Squares   F-statistic:                     1318.
Date:                Sat, 11 Apr 2020   Prob (F-statistic):               0.00
Time:                        20:20:25   Log-Likelihood:                -6299.3
No. Observations:                2000   AIC:                         1.261e+04
Df Residuals:                    1996   BIC:                         1.263e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      58.7621      0.466    126.172      0.000      57.849      59.676
exercise        0.9840      0.089     11.073      0.000       0.810       1.158
hours           1.9170      0.031     61.628      0.000       1.856       1.978
gender_male    -0.4476      0.253     -1.770      0.077      -0.943       0.048
==============================================================================
Omnibus:                      322.999   Durbin-Watson:                   2.048
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2244.206
Skew:                          -0.566   Prob(JB):                         0.00
Kurtosis:                       8.064   Cond. No.                         45.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""